ALTER TABLE `his`.`zl_rwfp`
    ADD COLUMN `YZ_JLXH` int(0) NOT NULL COMMENT '医嘱记录序号' AFTER `ZYH`,
    MODIFY COLUMN `ZLLB` int(0) NULL COMMENT '治疗类别' AFTER `ZYH`,
    MODIFY COLUMN `ZLZID` int(0) NULL COMMENT '治疗小组ID' AFTER `FPZT`,
    MODIFY COLUMN `ZLSDM` int(0) NULL COMMENT '治疗师代码' AFTER `ZLZID`,
    MODIFY COLUMN `FPSJ` datetime(0) NULL COMMENT '分配时间' AFTER `ZLSDM`;