ALTER TABLE `his`.`zl_zlpc`
    MODIFY COLUMN `ZLSDM` int(0) NOT NULL COMMENT '治疗师代码' AFTER `JLXH`,
    ADD COLUMN `ZYH` int(0) NOT NULL COMMENT '住院号' AFTER `ZLSDM`,
    MODIFY COLUMN `ZLRQ` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '治疗日期' AFTER `ZLKSDM`,
    MODIFY COLUMN `ZFPB` tinyint(1) NOT NULL COMMENT '作废判别 | 0：启用    1：作废' AFTER `SJJSSJ`;