ALTER TABLE `his`.`zl_rwmb`
    DROP COLUMN `SFXMDM`,
    DROP COLUMN `SFXMMC`,
    DROP COLUMN `SL`,
    DROP COLUMN `JE`,
    ADD COLUMN `SCZXRQ` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '首次执行日期' AFTER `BZXX`;

ALTER TABLE `his`.`zl_zlpc`
    MODIFY COLUMN `ZLRQ` varchar(10) NULL DEFAULT NULL COMMENT '治疗日期' AFTER `ZLKSDM`,
    MODIFY COLUMN `KSSJ` varchar(10) NULL DEFAULT NULL COMMENT '开始时间' AFTER `ZLRQ`,
    MODIFY COLUMN `JSSJ` varchar(10) NULL DEFAULT NULL COMMENT '结束时间' AFTER `KSSJ`;