ALTER TABLE `ss_ssjzdmx`
ADD COLUMN `JZ_JLXH` int NULL COMMENT '记账记录序号' AFTER `YTFSL`;
ALTER TABLE `ss_ssjzdmx`
MODIFY COLUMN `SFXMLB` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '收费项目类别,1:材料，2：项目，3：药品' AFTER `XH`,
ADD COLUMN `ssys` int NULL COMMENT '手术医生' AFTER `JZ_JLXH`;