ALTER TABLE `his`.`ss_ssjzdmx`
    ADD COLUMN `JZRDM` int(0)      NULL DEFAULT NULL COMMENT '记账人' AFTER `YPLX`,
    ADD COLUMN `JZSJ`  datetime(0) NULL DEFAULT NULL COMMENT '记账时间' AFTER `JZRDM`,
    DROP COLUMN `YTFSL`,
    MODIFY COLUMN `JZ_JLXH` int(0) NULL DEFAULT NULL COMMENT '记账明细记录序号' AFTER `ZT`;